DESCRIPTION = "Protocol Buffers are Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data."
HOMEPAGE = "https://developers.google.com/protocol-buffers/"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=35953c752efc9299b184f91bef540095"

SRC_URI = "gitsm://github.com/google/protobuf.git"
SRCREV = "1a586735085e817b1f52e53feec92ce418049f69"

PV = "3.0.2"

S = "${WORKDIR}/git"