DESCRIPTION = "Protocol Buffers are Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data."
HOMEPAGE = "https://developers.google.com/protocol-buffers/"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=35953c752efc9299b184f91bef540095"

PV = "3.3.0"

SRC_URI = "git://github.com/google/protobuf.git"
SRCREV = "a6189acd18b00611c1dc7042299ad75486f08a1a"

S = "${WORKDIR}/git"
