DESCRIPTION = "Measures number of Terminal column cells of wide-character codes"
HOMEPAGE = "https://github.com/jquast/wcwidth"
AUTHOR = "Jeff Quast"
SECTION = "devel/python"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=11fba47286258744a6bc6e43530c32a1"

PR = "r0"

SRC_URI = "git://github.com/jquast/wcwidth.git"
SRCREV = "c71459ea91af86f3bbcdac2c8ed5e7773da2d848"

S = "${WORKDIR}/git"
