SUMMARY = "Converts a Python dictionary or other native data type into a valid XML string."
AUTHOR = "Ryan McGreal"
HOMEPAGE = "https://github.com/quandyfactory/dicttoxml"
LICENSE = "GPL-2.0"
LIC_FILES_CHKSUM = "file://LICENCE.txt;md5=8c6f370c9073badc24ad75afa6822bcb"

PR = "r0"

SRC_URI = "git://github.com/quandyfactory/dicttoxml.git"
SRCREV = "2016fe9817ad03b26aa5f1a475f5b79ad6757b96"

S = "${WORKDIR}/git"
