DESCRIPTION = "Python interface to the Google WebRTC Voice Activity Detector (VAD)"
HOMEPAGE = "https://github.com/wiseman/py-webrtcvad"
AUTHOR = "John Wiseman"
SECTION = "devel/python"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=425b45e5a79ac786f2f8e977a3beaad4"

PR = "r0"

SRC_URI = "git://github.com/wiseman/py-webrtcvad.git"
SRCREV = "bb429dac1a686807c69b916f03dd843fa10b0927"

S = "${WORKDIR}/git"
